<?php

  $url = $this->getUrlStelo();
 if(Mage::getStoreConfig("payment/sso/active")){
     

?>
<script type="text/javascript">

  var html = '<a href="<?php echo $url ?>" id="light-wallet"  lightbox="true" class="openLightbox">';
      html += '<img width="130" style="float:right" alt="Logar com Stelo" src="<?php echo $this->getSkinUrl('wallet/images/logar_stelo_1.png') ?>" />';
      html += '</a>';



var field = $$('.col-2 .buttons-set')[0];
    if (field == undefined){
        field = $$('.form-list')[0];
    }
    field.insert(html);

  jQuery('#light-wallet').click(function(){
    jQuery.featherlight( jQuery('<iframe width="950" height="620" src="' + jQuery(this).attr('href') + '"/>') )
    return false;
  })

</script>
<?php  } ?>

